### ISSUE TITLE
Contact Form not appearing in Contact page

### ISSUE THREAD

**Issue by Kefle** [spicygreenbook/greenbook#14] opened 2020-09-17 07:07 UTC
Page: https://spicygreenbook.com/contact
Browsers used: Google Chrome Version 85.0.4183.102 (Official Build) (64-bit) and Safari Version 13.1.2 (15609.3.5.1.3)

Steps:
1. Click on Contact link (below right) from homepage
2. Upon landing on Contact page per URL above, Contact Form does not appear
3. However, Contact Form appears after refreshing page

**Comment by nealrosen** [comment] 2020-09-17 19:23
This appears to be caused by the way pages are loaded.  The [placement-controller.min.js](https://widget.honeybook.com/assets_users_production/websiteplacements/placement-controller.min.js) script file referenced below is loaded when the web app first loads.  This script file is self executing.  It uses a global window._HB_ property to determine what content to load and in which element on the page to insert the content.  One example of content loaded by this script is the contact form within the contact page.

There are 2 ways a page may load.  Directly as the first page loaded on the site (typed into the address bar). And indirectly by clicking on a navigation link from a different page on the same site.

**Scenario 1 (directly loading a page by entering the URL to a specific page)**
This scenario works fine.  The page loads, the window._HB_ value is set, then the placement-controller.min.js script is loaded.  When that script loads, the DOM is ready and the window._HB_ value is set for this page so the script file is able to load the appropriate content.

**Scenario 2 (indirectly loading a page from a navigation link)**
This scenario does not work.  The placement-controller.min.js script only loads once, even if multiple script tags are dynamically added to the page.  So, PageA loads, then the placement-controller script loads rendering content for PageA.  The user then navigates to PageB.  The site does not do a full refresh.  It dynamically swaps out the content based on the current route.  PageB updates window._HB_, then adds a script tag to load the placement-controller script, but this time that script does not load or run.  The result is that the content referenced by the _HB_ value does not get rendered.

Possible solutions include
1. Replacing (or updating) the next/Link components used for navigation to force a full refresh when switching pages
2. Updating the placement-controller script to support a way to execute multiple times (whenever the route/page changes)

**Comment by pleaseshutup** [comment] 2020-09-18 15:49
Thank you so much @nealrosen for this deatiled report. It clued me in to the bug being related to nextjs and not executing the provided honeybook.com script tag after a nextjs route navigation. It would work upon a direct page load from nextjs SSR but not when navigating to it. This is now fixed.

**Closed by pleaseshutup** 2020-09-18 15:49 UTC
